In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
# import sqlite3
# import pandas as pd

# db_path = '/content/drive/MyDrive/Machine learning projects/Database.db'

# conn = sqlite3.connect(db_path)

# data = pd.read_sql_query('SELECT * FROM Automobile_data', conn)

In [3]:
# conn.close()

In [4]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('Database.db')
data = pd.read_sql_query('SELECT * FROM Automobile_data', conn)

## Load the dataset

In [5]:

data.head(11)

,r,m (kg),Mt,Ewltp (g/km),Ft,Fm,ec (cm3),ep (KW),z (Wh/km),Erwltp (g/km),Fuel consumption,Electric range (km)
0,1,1262.0,1352.0,133.0,petrol,M,999.0,84.0,NaN,1.56,5.8,NaN
1,1,2434.0,2559.0,0.0,electric,E,NaN,300.0,193.0,NaN,NaN,445.0
2,1,1984.0,2095.0,0.0,electric,E,NaN,220.0,157.0,NaN,NaN,455.0
3,1,1314.0,1386.0,149.0,petrol,M,1498.0,78.0,NaN,NaN,6.6,NaN
4,1,1075.0,1145.0,119.0,lpg,B,1242.0,51.0,NaN,NaN,6.0,NaN
5,1,1055.0,1177.0,123.0,petrol,M,1199.0,61.0,NaN,1.91,5.5,NaN
6,1,1165.0,1317.0,112.0,diesel,M,1499.0,75.0,NaN,1.76,4.3,NaN
7,1,2065.0,2156.0,45.0,petrol/electric,P,1998.0,120.0,190.0,NaN,2.0,49.0
8,1,1653.0,1775.0,24.0,petrol/electric,P,1395.0,110.0,148.0,NaN,1.1,63.0
9,1,1620.0,1717.0,127.0,diesel,M,1995.0,110.0,NaN,1.83,4.8,NaN
10,1,1200.0,1328.0,123.0,petrol,M,998.0,74.0,NaN,1.43,5.4,NaN

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   r                    1000000 non-null  int64
 1   m (kg)               999961 non-null   float64
 2   Mt                   951692 non-null   float64
 3   Ewltp (g/km)         998031 non-null   float64
 4   Ft                   1000000 non-null  str
 5   Fm                   1000000 non-null  str
 6   ec (cm3)             844323 non-null   float64
 7   ep (KW)              996696 non-null   float64
 8   z (Wh/km)            219176 non-null   float64
 9   Erwltp (g/km)        537925 non-null   float64
 10  Fuel consumption     703248 non-null   float64
 11  Electric range (km)  216965 non-null   float64
dtypes: float64(9), int64(1), str(2)
memory usage: 99.1 MB

## Preprocessing: Handling missing values and encoding

In [7]:
data.isnull().sum()

r                           0
m (kg)                     39
Mt                      48308
Ewltp (g/km)             1969
Ft                          0
Fm                          0
ec (cm3)               155677
ep (KW)                  3304
z (Wh/km)              780824
Erwltp (g/km)          462075
Fuel consumption       296752
Electric range (km)    783035
dtype: int64

In [8]:
# 1. Sabse pehle 'r' column uda do kyunki iski importance 0 hai
if 'r' in data.columns:
    data = data.drop(columns=['r'])

# 2. Jo cars electric nahi hain, unki range aur z value 0 karo
data.loc[data['Ft'] != 'electric', 'Electric range (km)'] = 0
data.loc[data['Ft'] != 'electric', 'z (Wh/km)'] = 0

# 3. Agar target column 'Fuel consumption ' hi missing hai, toh wo row hata do
data = data.dropna(subset=['Fuel consumption '])

In [9]:
data.isnull().sum()

m (kg)                     21
Mt                      12718
Ewltp (g/km)              326
Ft                          0
Fm                          0
ec (cm3)                   27
ep (KW)                     1
z (Wh/km)                   0
Erwltp (g/km)          198486
Fuel consumption            0
Electric range (km)         0
dtype: int64

In [10]:
# LabelEncoder ki jagah Get Dummies (One-Hot Encoding)
data = pd.get_dummies(data, columns=['Ft', 'Fm'], drop_first=True)

In [11]:
data.head(11)

,m (kg),Mt,Ewltp (g/km),ec (cm3),ep (KW),z (Wh/km),Erwltp (g/km),Fuel consumption,Electric range (km),Ft_PETROL,...,Ft_hydrogen,Ft_lpg,Ft_ng,Ft_petrol,Ft_petrol/electric,Fm_E,Fm_F,Fm_H,Fm_M,Fm_P
0,1262.0,1352.0,133.0,999.0,84.0,0.0,1.56,5.8,0.0,False,...,False,False,False,True,False,False,False,False,True,False
3,1314.0,1386.0,149.0,1498.0,78.0,0.0,NaN,6.6,0.0,False,...,False,False,False,True,False,False,False,False,True,False
4,1075.0,1145.0,119.0,1242.0,51.0,0.0,NaN,6.0,0.0,False,...,False,True,False,False,False,False,False,False,False,False
5,1055.0,1177.0,123.0,1199.0,61.0,0.0,1.91,5.5,0.0,False,...,False,False,False,True,False,False,False,False,True,False
6,1165.0,1317.0,112.0,1499.0,75.0,0.0,1.76,4.3,0.0,False,...,False,False,False,False,False,False,False,False,True,False
7,2065.0,2156.0,45.0,1998.0,120.0,0.0,NaN,2.0,0.0,False,...,False,False,False,False,True,False,False,False,False,True
8,1653.0,1775.0,24.0,1395.0,110.0,0.0,NaN,1.1,0.0,False,...,False,False,False,False,True,False,False,False,False,True
9,1620.0,1717.0,127.0,1995.0,110.0,0.0,1.83,4.8,0.0,False,...,False,False,False,False,False,False,False,False,True,False
10,1200.0,1328.0,123.0,998.0,74.0,0.0,1.43,5.4,0.0,False,...,False,False,False,True,False,False,False,False,True,False
11,1615.0,1702.0,141.0,1598.0,96.0,0.0,1.56,5.4,0.0,False,...,False,False,False,False,False,False,False,False,True,False
13,1236.0,1397.0,134.0,999.0,81.0,0.0,1.90,5.9,0.0,False,...,False,False,False,True,False,False,False,False,True,False

## Seprating features and target

In [12]:
X = data.drop(columns=['Fuel consumption '])
y = data['Fuel consumption ']

In [13]:
feature_names = X.columns

## Train test and split

In [14]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, test_size = 0.2, random_state = 42)

## Feature Scaling

In [15]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

x_train_imputed = imputer.fit_transform(x_train)
x_test_imputed = imputer.transform(x_test)

## Initializing and training the model

In [16]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train_imputed, y_train)

RandomForestRegressor(random_state=42)

## Make predictions on the test set

In [17]:
y_pred = model.predict(x_test_imputed)

## Evaluate the model

In [18]:
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [19]:
print(f'Mean Squared Error (MSE): {mse}')
print(f'Root Mean Squared Error (RMSE): {rmse}')
print(f'Mean Absolute Error (MAE): {mae}')
print(f'R-squared (R²): {r2}')

Mean Squared Error (MSE): 0.02156073052190167
Root Mean Squared Error (RMSE): 0.14683572631312064
Mean Absolute Error (MAE): 0.024180680384330085
R-squared (R²): 0.9932654721693356

## Feature importance

In [24]:
# import pandas as pd
# import matplotlib.pyplot as plt

# features = feature_names

# feature_importance = model.feature_importances_

# assert len(features) == len(feature_importance), "Number of features does not match the number of importances"

# importance_df = pd.DataFrame({
#     'Feature': features,
#     'Importance': feature_importance
# })

# importance_df = importance_df.sort_values(by='Importance', ascending=False)

# print(importance_df)

# # Plot the feature importance
# plt.figure(figsize=(10, 6))
# plt.barh(importance_df['Feature'], importance_df['Importance'], color='skyblue')
# plt.xlabel('Importance')
# plt.title('Feature Importance')
# plt.gca().invert_yaxis()
# plt.show()

## Saving the trained model

In [21]:
import joblib
joblib.dump(model, 'fuel_consumption_modelv1.pkl')
joblib.dump(imputer, 'imputerv1.pkl')

['imputerv1.pkl']

In [26]:
import pandas as pd
import joblib

def predict_fuel_eff(input_data_df):
    loaded_model = joblib.load('fuel_consumption_modelv1.pkl')
    loaded_imputer = joblib.load('imputerv1.pkl')


    input_ready = loaded_imputer.transform(input_data_df)

    # 3. Final prediction nikalo
    prediction = loaded_model.predict(input_ready)
    return prediction[0]
input_data = x_test.iloc[[0]]

predicted_fuel_consumption = predict_fuel_eff(input_data)

print(f"Predicted Fuel Consumption: {predicted_fuel_consumption}")

Predicted Fuel Consumption: 5.800000000000001